# General
work_dir: ./work_dir/signal_length_1000
num_epoch: 150
save_interval: 10
eval_interval: 1

# Dataloader
train_batch_size: 16
test_batch_size: 16
take_n_examples: -1

# Model
input_window_size: [1000, 6]
model: model.hierarchical_CNN_SeLU.Model
model_args:
  f_1: 32
  f_2: 32
  f_3: 32
  f_4: 32
  f_5: 32

  nb_class: 27
  bin_layer: 256
  multi_layer: 512



# Initialization
weights: './model/saved_model/epoch90_model.pt'

phase: test


# Optimizer
optimizer: torch.optim.SGD
loss: torch.nn.CrossEntropyLoss
binary_weights: [0.0385, 1]
optimizer_args:
  lr: 0.0

# Schedule
num_worker: 4
scheduler: torch.optim.lr_scheduler.ExponentialLR
scheduler_args:
  gamma: 0.99











